
build:
  main: cmd/syslog-cloudlogs/main.go
  binary: /syslog-cloudlogs
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
dockers:
  - image: versent/syslog-cloudlogs
    latest: true
fpm:
  homepage: https://github.com/versent/syslog-cloudlogs
  license: MIT
  formats:
    - deb
    - rpm
  bindir: /usr/bin
  files:
    "scripts/etc/systemd/system": "/etc/systemd/system"
    "scripts/etc/syslog-cloudlogs": "/etc/syslog-cloudlogs"
